StrucInfo:
  struct:
    element: Pt
    lattype: fcc
    latcont: 4.16
    facet: ['100']
    dope:
      Cu: ['0']

Model:
  ads:
    - ['OH',1]
    - ['O2',1]
    - ['H2',1]
    - ['H2O',1]
    - ['CO2',1]
    - ['CO',1]
  coads:
    - ['O','H',1,1]