StrucInfo:
  struct:
    element: Au
    lattype: fcc
    latcont: 4.16
    facet: ['111']
    dope:
      Cu: [3]

Model:
  coads:
    - [s: 'N',s: '[O]',1,1]
    - [s: '[NH2]',s: '[OH]',1,1]
    - [s: '[N]',s: '[N]',1,1]
    - [s: '[N]',s: '[O]',1,1]
    - [s: '[N]',s: '[N]=O',1,1]