StrucInfo:
  struct:
    element: Au
    lattice_type: fcc
    lattice_constant: 4.16
    facet: ["111", "100"]
    dope:
      Cu: [3]

Model:
  ads:
    - ["NH3", 1]
  coads:
    - ["NH3", "O", 1, 1]
