StrucInfo:
  struct:
    element: Pt
    lattice_type: fcc
    lattice_constant: 3.92
    facet: ["111"]
    supercell: [3, 3]
    layers: 4
    dope:
      Cu: [0]

# Default format is simple if don't define this part
Species:
  file:
    "NH3+": NH3+.xyz #struct_file
  sml:
    "O2": O=O #smiles

Model:
  ads:
    - ["NH3+", 1]
    - [f: "NH3-.xyz", 1]
    - ["NO", 2]
    - ["O2", 2]
    - [s: "O=O", 1]
